//! lava-spec — typed substrate meta-spec for the lava + tatara-lisp
//! ecosystem per ★★ CATALOG REFLECTION.
//!
//! Every authored primitive ships a typed [`CatalogEntry`]. The
//! [`Catalog`] aggregates them; consumer tools (operator CLIs, drift
//! detectors, autogen pipelines, docs) iterate the catalog
//! mechanically instead of doing string-name lookups across the
//! codebase.
//!
//! ## Primitive kinds
//!
//! See [`PrimitiveKind`] for the closed list. Today's lava ecosystem
//! ships:
//!
//! | Kind            | Authoring form            | Crate                    |
//! |---|---|---|
//! | Architecture    | `(deflava-architecture …)`| `lava-architectures`     |
//! | Interface       | `(deflava-interface …)`   | `lava-eval` (parser)     |
//! | Resource        | `(deflava-resource …)`    | `lava-forge` (autogen)   |
//! | Provider        | `(deflava-provider …)`    | `lava-forge` (aggregator)|
//! | Stack           | `(deflava-stack …)`       | `lava-stack`             |
//! | Test            | `(deflava-test …)`        | `lava-test`              |
//! | ApiOperation    | `(defapi-operation …)`    | `lava-api-forge`         |
//! | ApiShape        | `(defapi-shape …)`        | `lava-api-forge`         |
//! | Module          | `(deflava-module …)`      | planned                  |
//! | Function        | `(deflava-function …)`    | planned                  |
//! | Spec            | `(deflava-spec …)`        | planned                  |
//! | Template        | `(deflava-template …)`    | planned                  |
//!
//! ## CATALOG REFLECTION invariants (provided by [`Catalog::verify`])
//!
//! 1. Every entry has a non-empty name.
//! 2. Authoring keywords are globally unique within their kind.
//! 3. Every `depends_on` reference resolves to another entry.
//! 4. The dependency graph has no cycles (topological order solvable).
//! 5. Maturity histogram sums to the catalog size (partition complete).

#![allow(clippy::module_name_repetitions)]

use serde::{Deserialize, Serialize};
use std::collections::{BTreeMap, HashSet};
use thiserror::Error;

/// Closed list of typed primitive kinds the lava ecosystem ships.
/// New variants land here when a new typed form is introduced.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "kebab-case")]
pub enum PrimitiveKind {
    /// `(deflava-architecture …)` — top-level composition.
    Architecture,
    /// `(deflava-interface …)` — typed input/output contract.
    Interface,
    /// `(deflava-resource …)` — autogenerated typed resource shape.
    Resource,
    /// `(deflava-provider …)` — provider aggregator (resource catalog).
    Provider,
    /// `(deflava-stack …)` — deployment instance.
    Stack,
    /// `(deflava-module …)` — reusable sub-architecture.
    Module,
    /// `(deflava-function …)` — typed pure transformation.
    Function,
    /// `(deflava-test …)` — typed assertion test suite.
    Test,
    /// `(deflava-spec …)` — BDD-style scenario.
    Spec,
    /// `(deflava-template …)` — scaffold for new components.
    Template,
    /// `(defapi-operation …)` — REST/RPC operation binding.
    ApiOperation,
    /// `(defapi-shape …)` — request/response/data shape binding.
    ApiShape,
}

impl PrimitiveKind {
    /// The tatara-lisp authoring keyword for this kind (e.g.
    /// `deflava-architecture`).
    #[must_use]
    pub const fn keyword(self) -> &'static str {
        match self {
            Self::Architecture => "deflava-architecture",
            Self::Interface => "deflava-interface",
            Self::Resource => "deflava-resource",
            Self::Provider => "deflava-provider",
            Self::Stack => "deflava-stack",
            Self::Module => "deflava-module",
            Self::Function => "deflava-function",
            Self::Test => "deflava-test",
            Self::Spec => "deflava-spec",
            Self::Template => "deflava-template",
            Self::ApiOperation => "defapi-operation",
            Self::ApiShape => "defapi-shape",
        }
    }

    /// Iterate every known kind.
    pub fn all() -> [PrimitiveKind; 12] {
        [
            Self::Architecture,
            Self::Interface,
            Self::Resource,
            Self::Provider,
            Self::Stack,
            Self::Module,
            Self::Function,
            Self::Test,
            Self::Spec,
            Self::Template,
            Self::ApiOperation,
            Self::ApiShape,
        ]
    }
}

/// Maturity gate per entry. Mechanical readiness signal that lets
/// tooling plan implementation order + filter by stability.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord, Serialize, Deserialize)]
#[serde(rename_all = "kebab-case")]
pub enum Maturity {
    Production,
    Beta,
    Alpha,
    Planned,
    Deprecated,
}

/// One catalog entry. Names + describes a single typed primitive.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct CatalogEntry {
    pub name: String,
    pub kind: PrimitiveKind,
    pub maturity: Maturity,
    pub purpose: String,
    /// e.g. "pangea-architectures/cloudflare_dns_records.rb" — the
    /// upstream shape this entry mirrors, if any.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub upstream_mirror: Option<String>,
    /// Names of other entries this one consumes. Forms the typed DAG.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub depends_on: Vec<String>,
}

impl CatalogEntry {
    #[must_use]
    pub fn new(
        name: impl Into<String>,
        kind: PrimitiveKind,
        maturity: Maturity,
        purpose: impl Into<String>,
    ) -> Self {
        Self {
            name: name.into(),
            kind,
            maturity,
            purpose: purpose.into(),
            upstream_mirror: None,
            depends_on: Vec::new(),
        }
    }

    #[must_use]
    pub fn mirroring(mut self, source: impl Into<String>) -> Self {
        self.upstream_mirror = Some(source.into());
        self
    }

    #[must_use]
    pub fn depending_on(mut self, deps: &[&str]) -> Self {
        self.depends_on = deps.iter().map(|s| (*s).to_string()).collect();
        self
    }
}

/// Catalog of typed primitives across the lava substrate.
#[derive(Debug, Default, Clone, Serialize, Deserialize)]
pub struct Catalog {
    pub entries: Vec<CatalogEntry>,
}

impl Catalog {
    #[must_use]
    pub fn new() -> Self {
        Self::default()
    }

    pub fn push(&mut self, e: CatalogEntry) {
        self.entries.push(e);
    }

    /// Find an entry by name. Returns the first match.
    #[must_use]
    pub fn find(&self, name: &str) -> Option<&CatalogEntry> {
        self.entries.iter().find(|e| e.name == name)
    }

    /// Filter entries by kind.
    pub fn of_kind(&self, kind: PrimitiveKind) -> impl Iterator<Item = &CatalogEntry> {
        self.entries.iter().filter(move |e| e.kind == kind)
    }

    /// Histogram of maturity → count. Sum equals entries.len() iff
    /// every entry has a known maturity (always the case via the
    /// closed enum).
    #[must_use]
    pub fn maturity_histogram(&self) -> BTreeMap<Maturity, usize> {
        let mut out: BTreeMap<Maturity, usize> = BTreeMap::new();
        for e in &self.entries {
            *out.entry(e.maturity).or_insert(0) += 1;
        }
        out
    }

    /// Topological order over the dependency edges. Returns None if a
    /// cycle exists.
    #[must_use]
    pub fn topological_order(&self) -> Option<Vec<&CatalogEntry>> {
        let mut visited: HashSet<(PrimitiveKind, String)> = HashSet::new();
        let mut on_stack: HashSet<(PrimitiveKind, String)> = HashSet::new();
        let mut out: Vec<&CatalogEntry> = Vec::new();
        for e in &self.entries {
            if !visit(e, self, &mut visited, &mut on_stack, &mut out) {
                return None;
            }
        }
        Some(out)
    }

    /// Run every typed CATALOG REFLECTION invariant. Returns the full
    /// list of violations (empty = catalog passes).
    ///
    /// # Errors
    /// `Err(violations)` lists every typed [`CatalogError`] caught.
    pub fn verify(&self) -> Result<(), Vec<CatalogError>> {
        let mut errs: Vec<CatalogError> = Vec::new();

        // 1. Names non-empty.
        for e in &self.entries {
            if e.name.trim().is_empty() {
                errs.push(CatalogError::EmptyName);
            }
        }

        // 2. Keyword uniqueness within kind.
        let mut seen: HashSet<(PrimitiveKind, String)> = HashSet::new();
        for e in &self.entries {
            let key = (e.kind, e.name.clone());
            if !seen.insert(key) {
                errs.push(CatalogError::DuplicateName {
                    name: e.name.clone(),
                    kind: e.kind,
                });
            }
        }

        // 3. Every depends_on edge resolves to another entry.
        for e in &self.entries {
            for dep in &e.depends_on {
                if self.find(dep).is_none() {
                    errs.push(CatalogError::DanglingDependency {
                        from: e.name.clone(),
                        to: dep.clone(),
                    });
                }
            }
        }

        // 4. No cycles.
        if self.topological_order().is_none() {
            errs.push(CatalogError::Cycle);
        }

        // 5. Maturity histogram sums to entries.len().
        let sum: usize = self.maturity_histogram().values().sum();
        if sum != self.entries.len() {
            errs.push(CatalogError::MaturityHistogramMismatch {
                sum,
                entries: self.entries.len(),
            });
        }

        if errs.is_empty() {
            Ok(())
        } else {
            Err(errs)
        }
    }
}

fn visit<'a>(
    entry: &'a CatalogEntry,
    catalog: &'a Catalog,
    visited: &mut HashSet<(PrimitiveKind, String)>,
    on_stack: &mut HashSet<(PrimitiveKind, String)>,
    out: &mut Vec<&'a CatalogEntry>,
) -> bool {
    let key = (entry.kind, entry.name.clone());
    if visited.contains(&key) {
        return true;
    }
    if !on_stack.insert(key.clone()) {
        return false; // cycle
    }
    for dep_name in &entry.depends_on {
        if let Some(dep) = catalog.find(dep_name) {
            if !visit(dep, catalog, visited, on_stack, out) {
                return false;
            }
        }
    }
    on_stack.remove(&key);
    visited.insert(key);
    out.push(entry);
    true
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, Error)]
pub enum CatalogError {
    #[error("entry has empty name")]
    EmptyName,
    #[error("duplicate `{name}` in kind `{kind:?}`")]
    DuplicateName { name: String, kind: PrimitiveKind },
    #[error("`{from}` depends_on `{to}` which is not in the catalog")]
    DanglingDependency { from: String, to: String },
    #[error("dependency graph contains a cycle")]
    Cycle,
    #[error("maturity histogram sums to {sum}, expected {entries}")]
    MaturityHistogramMismatch { sum: usize, entries: usize },
}

/// Bundled catalog for the lava + tatara-lisp substrate. Names every
/// shipped + planned primitive across the suite.
#[must_use]
pub fn bundled_catalog() -> Catalog {
    let mut c = Catalog::new();
    // ── Architecture (one entry per bundled architecture) ──────
    let architectures = [
        ("aws-vpc-network", "Standard AWS VPC + IGW + subnets + NAT"),
        ("cloudflare-dns-records", "Cloudflare DNS records bundle"),
        ("akeyless-secrets", "Akeyless secrets: auth + targets + role"),
        ("cloudflare-r2-bucket", "R2 bucket + CORS + custom domain + CNAME"),
        ("public-dns", "Route53 public zone + DNSSEC + query log"),
        ("akeyless-platform", "Akeyless platform: ACM + Route53 + IAM"),
    ];
    for (name, purpose) in architectures {
        c.push(CatalogEntry::new(
            name,
            PrimitiveKind::Architecture,
            Maturity::Beta,
            purpose,
        ));
    }
    // ── Interface (paired with each Architecture) ──────────────
    for (name, _) in architectures {
        c.push(
            CatalogEntry::new(
                name,
                PrimitiveKind::Interface,
                Maturity::Beta,
                "Typed input/output contract",
            )
            .depending_on(&[]), // The interface defines the contract; arch consumes it implicitly.
        );
    }
    // ── Test (one suite per Architecture) ──────────────────────
    for (name, _) in architectures {
        c.push(
            CatalogEntry::new(
                name,
                PrimitiveKind::Test,
                Maturity::Beta,
                "Typed assertion suite",
            )
            .depending_on(&[name]), // Test depends on the Architecture it covers.
        );
    }
    // ── Stack: the deployment-instance form lives in lava-stack ─
    c.push(
        CatalogEntry::new(
            "lava-stack",
            PrimitiveKind::Stack,
            Maturity::Beta,
            "Deployment instance — architecture × backend × workspace",
        )
        .mirroring("pangea-stack"),
    );
    // ── API forge primitives ───────────────────────────────────
    c.push(
        CatalogEntry::new(
            "lava-api-forge",
            PrimitiveKind::ApiOperation,
            Maturity::Alpha,
            "OpenAPI/botocore → typed (defapi-operation …)",
        )
        .mirroring("aws-sdk-go (botocore JSON)"),
    );
    c.push(
        CatalogEntry::new(
            "lava-api-forge",
            PrimitiveKind::ApiShape,
            Maturity::Alpha,
            "OpenAPI/botocore → typed (defapi-shape …)",
        )
        .mirroring("aws-sdk-go (botocore JSON)"),
    );
    // ── Provider + Resource: emitted by lava-forge per provider ─
    c.push(CatalogEntry::new(
        "aws",
        PrimitiveKind::Provider,
        Maturity::Beta,
        "Cataloger of autogenerated aws_* resource shapes",
    ));
    // One typed Resource entry per canonical lava-forge-generated
    // shape, mirroring the terraform provider's resource block.
    for (name, purpose) in [
        ("aws-vpc", "Virtual Private Cloud"),
        ("aws-subnet", "Subnet"),
        ("aws-internet-gateway", "Internet Gateway"),
        ("cloudflare-r2-bucket", "R2 storage bucket"),
        ("cloudflare-dns-record", "DNS record"),
        ("akeyless-static-secret", "Static secret value"),
    ] {
        c.push(
            CatalogEntry::new(name, PrimitiveKind::Resource, Maturity::Beta, purpose)
                .mirroring("terraform provider schema"),
        );
    }
    // ── Planned primitives ────────────────────────────────────
    for (name, purpose) in [
        ("deflava-module", "Reusable sub-architecture; terraform-module analog"),
        ("deflava-function", "Typed pure transformation (cidr-add, hash, etc.)"),
        ("deflava-spec", "BDD-style behavioral scenario"),
        ("deflava-template", "Scaffold for autogenerating new components"),
    ] {
        let kind = match name {
            "deflava-module" => PrimitiveKind::Module,
            "deflava-function" => PrimitiveKind::Function,
            "deflava-spec" => PrimitiveKind::Spec,
            "deflava-template" => PrimitiveKind::Template,
            _ => unreachable!(),
        };
        c.push(CatalogEntry::new(
            name,
            kind,
            Maturity::Planned,
            purpose,
        ));
    }
    c
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn bundled_catalog_passes_every_reflection_invariant() {
        let cat = bundled_catalog();
        cat.verify().unwrap();
    }

    #[test]
    fn bundled_catalog_covers_every_primitive_kind_planned_or_shipped() {
        let cat = bundled_catalog();
        let seen: HashSet<PrimitiveKind> = cat.entries.iter().map(|e| e.kind).collect();
        for k in PrimitiveKind::all() {
            assert!(
                seen.contains(&k),
                "catalog missing entry for {k:?} — every kind needs at least one entry (planned ok)"
            );
        }
    }

    #[test]
    fn architecture_test_pairing_holds_for_every_bundled_arch() {
        let cat = bundled_catalog();
        let archs: HashSet<&str> = cat
            .of_kind(PrimitiveKind::Architecture)
            .map(|e| e.name.as_str())
            .collect();
        for arch in &archs {
            assert!(
                cat.entries
                    .iter()
                    .any(|e| e.kind == PrimitiveKind::Test && e.name == *arch),
                "architecture `{arch}` has no paired Test entry"
            );
        }
    }

    #[test]
    fn topological_order_visits_every_entry_with_deps_satisfied() {
        let cat = bundled_catalog();
        let order = cat.topological_order().unwrap();
        assert_eq!(order.len(), cat.entries.len());
        // Validate the order — every dep appears before its dependent.
        let positions: BTreeMap<&str, usize> = order
            .iter()
            .enumerate()
            .map(|(i, e)| (e.name.as_str(), i))
            .collect();
        for e in &cat.entries {
            for dep in &e.depends_on {
                assert!(
                    positions[dep.as_str()] <= positions[e.name.as_str()],
                    "dep {dep} appears after {} in topo order",
                    e.name
                );
            }
        }
    }

    #[test]
    fn duplicate_name_within_kind_surfaces_typed_error() {
        let mut cat = Catalog::new();
        cat.push(CatalogEntry::new(
            "x",
            PrimitiveKind::Architecture,
            Maturity::Beta,
            "first",
        ));
        cat.push(CatalogEntry::new(
            "x",
            PrimitiveKind::Architecture,
            Maturity::Beta,
            "second",
        ));
        let errs = cat.verify().unwrap_err();
        assert!(errs.iter().any(|e| matches!(e, CatalogError::DuplicateName { .. })));
    }

    #[test]
    fn dangling_dependency_surfaces_typed_error() {
        let mut cat = Catalog::new();
        cat.push(
            CatalogEntry::new("a", PrimitiveKind::Architecture, Maturity::Beta, "")
                .depending_on(&["b-does-not-exist"]),
        );
        let errs = cat.verify().unwrap_err();
        assert!(errs
            .iter()
            .any(|e| matches!(e, CatalogError::DanglingDependency { .. })));
    }

    #[test]
    fn cycle_in_dependency_graph_surfaces_typed_error() {
        let mut cat = Catalog::new();
        cat.push(
            CatalogEntry::new("a", PrimitiveKind::Architecture, Maturity::Beta, "")
                .depending_on(&["b"]),
        );
        cat.push(
            CatalogEntry::new("b", PrimitiveKind::Architecture, Maturity::Beta, "")
                .depending_on(&["a"]),
        );
        let errs = cat.verify().unwrap_err();
        assert!(errs.iter().any(|e| matches!(e, CatalogError::Cycle)));
    }

    #[test]
    fn keyword_for_every_kind_is_stable_kebab_case() {
        for k in PrimitiveKind::all() {
            let kw = k.keyword();
            assert!(kw.starts_with("def"), "{kw:?} should start with `def`");
            assert!(kw.chars().all(|c| c.is_ascii_lowercase() || c == '-'));
        }
    }

    #[test]
    fn catalog_round_trips_through_serde_json() {
        let cat = bundled_catalog();
        let serialized = serde_json::to_string(&cat).unwrap();
        let parsed: Catalog = serde_json::from_str(&serialized).unwrap();
        assert_eq!(cat.entries.len(), parsed.entries.len());
    }
}
